language: node_js
node_js:
  - "9"
services:
  - mongodb
before_script:
  - sleep 15
after_success: 
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash -f "!socketsServer.js" -f "!image-service.js" -f "!mail.js")